import { access, readFile, readdir, writeFile } from 'node:fs/promises';
import { resolve } from 'node:path';

const sourceRoot = resolve(process.cwd(), 'studio/src/capabilities');
const outputPath = resolve(process.cwd(), 'studio/docs/ai-development/CAPABILITY-CATALOG.md');
const rows = [];
for (const entry of await readdir(sourceRoot, { withFileTypes: true })) {
  if (!entry.isDirectory()) continue;
  const manifestPath = resolve(sourceRoot, entry.name, 'manifest.ts');
  if (!await access(manifestPath).then(() => true, () => false)) continue;
  const source = await readFile(manifestPath, 'utf8');
  const id = source.match(/id:\s*'([^']+)'/)?.[1];
  const version = source.match(/version:\s*'([^']+)'/)?.[1];
  const dependencies = source.match(/dependsOn:\s*\[([^\]]*)\]/)?.[1]?.replaceAll("'", '').trim() || '—';
  if (!id || !version) throw new Error(`${entry.name}: manifest metadata not found`);
  rows.push(`| ${id} | ${version} | ${dependencies} | src/capabilities/${entry.name}/AGENTS.md |`);
}
rows.sort();
const content = `# Capability Catalog\n\n> Generated by \`npm run catalog:capabilities\`. Do not edit manually.\n\n| Capability | Version | Depends on | Local guide |\n| --- | --- | --- | --- |\n${rows.join('\n')}\n`;
if (process.argv.includes('--check')) {
  const current = await readFile(outputPath, 'utf8').catch(() => '');
  if (current.replaceAll('\r\n', '\n') !== content) { console.error('Capability Catalog is stale.'); process.exitCode = 1; }
} else { await writeFile(outputPath, content); console.log(`Wrote ${outputPath}`); }
